export class FontTypeConfig {

  static attendanceComponent = {
    traditional_Chinese:{
      tab1:'我的異常',
      tab2:'加班申請',
      tab3:'假單管理',
      tab4:'考勤查詢',
      tab5:'統計圖表'
    },
    simple_Chinese:{
      tab1:'我的异常',
      tab2:'加班申请',
      tab3:'假单管理',
      tab4:'考勤查询',
      tab5:'统计图表'
    }
  };

  static overTimeFormComponent = {
    traditional_Chinese:{
      unSave_title:'新建加班單',
      saved_title:'加班單詳情',
      form_status:'單據狀態',
      form_No:'單據編號',
      sign:'送簽',
      save:'保存',
      confirm:'確認',
      cancle:'取消',
      sign_list:'簽核名單',
      duty_type: '班別',
      OTtime:'加班日期',
      startTime:'起始時間',
      endTime:'結束時間',
      OTCount:'加班時數',
      reasonType:'工作紀要',
      reason:'加班原因',
      sign_success:'送簽成功',
      save_success:'表單保存成功',
      reasonType_required_err:'請選擇加班類型',
      OTtime_required_err:'加班日期不能為空',
      reason_required_err:'原因不能為空',
      reason_minlength_err:'原因長度不能少於2位',
      startTime_required_err:'開始時間不能為空',
      startTime_timeSmaller_err:'結束時間必須遲於開始時間',
      endTime_required_err:'結束時間不能為空',
      endTime_timeBigger_err:'結束時間必須遲於開始時間'
    },
    simple_Chinese:{
      unSave_title:'新建加班单',
      saved_title:'加班单详情',
      form_status:'单据状态',
      form_No:'单据编号',
      sign:'送签',
      save:'保存',
      confirm:'确认',
      cancle:'取消',
      sign_list:'签核名单',
      duty_type: '班别',
      OTtime:'加班日期',
      startTime:'起始时间',
      endTime:'结束时间',
      OTCount:'加班时数',
      reasonType:'工作纪要',
      reason:'加班原因',
      sign_success:'送签成功',
      save_success:'表单保存成功',
      reasonType_required_err:'请选择加班类型',
      OTtime_required_err:'加班日期不能为空',
      reason_required_err:'原因不能为空',
      reason_minlength_err:'原因长度不能少于2位',
      startTime_required_err:'开始时间不能为空',
      startTime_timeSmaller_err:'结束时间必须迟于开始时间',
      endTime_required_err:'结束时间不能为空',
      endTime_timeBigger_err:'结束时间必须迟于开始时间'
    }
  };

  static LeaveFormComponent = {
    traditional_Chinese:{
      unSave_title:'新建請假單',
      saved_title:'請假單詳情',
      form_status:'單據狀態',
      form_No:'單據編號',
      reasonType:'假別',
      autoSet:'代理人Template產生代理',
      startDate:'開始日期',
      endDate:'結束日期',
      startTime:'開始時間',
      endTime:'結束時間',
      colleague:'代理',
      leave_hour:'時數',
      leave_day:'日數',
      reason:'原因',
      sign:'送簽',
      save:'保存',
      sign_list:'簽核名單',
      reasonType_required_err:'請選擇請假類型',
      colleague_required_err:'請選擇代理人',
      reason_required_err: '原因不能為空',
      reason_minlength_err: '原因長度不能少於2位',
      sign_success:'送簽成功',
      save_success:'表單保存成功',
      time_err:'開始時間必須早於結束時間',
      colleague_placeholder:'請輸入2位以上的工號進行查詢',
      confirm:'確認',
      cancle:'取消'
    },
    simple_Chinese:{
      unSave_title:'新建请假单',
      saved_title:'请假单详情',
      form_status:'单据状态',
      form_No:'单据编号',
      reasonType:'假别',
      autoSet:'代理人Template產生代理',
      startDate:'开始日期',
      endDate:'结束日期',
      startTime:'开始时间',
      endTime:'结束时间',
      colleague:'代理',
      leave_hour:'时数',
      leave_day:'日数',
      reason:'原因',
      sign:'送签',
      save:'保存',
      sign_list:'签核名单',
      reasonType_required_err:'请选择请假类型',
      colleague_required_err:'请选择代理人',
      reason_required_err: '原因不能为空',
      reason_minlength_err: '原因长度不能少于2位',
      sign_success:'送签成功',
      save_success:'表单保存成功',
      time_err:'开始时间必须早于结束时间',
      colleague_placeholder:'请输入2位以上的工号进行查询',
      confirm:'确认',
      cancle:'取消'
    }
  };

}
