export class LanguageTypeConfig {

  static attendanceComponent = {
    traditional_Chinese:{
      tab1:'我的異常',
      tab2:'加班申請',
      tab3:'假單管理',
      tab4:'考勤查詢',
      tab5:'統計圖表'
    },
    simple_Chinese:{
      tab1:'我的异常',
      tab2:'加班申请',
      tab3:'假单管理',
      tab4:'考勤查询',
      tab5:'统计图表'
    }
  };
  static searchFormComponent = {
    traditional_Chinese:{
      title:'查詢',
      form_type:'單據類型',
      startTime:'假單管理',
      endTime:'考勤查詢',
      form_No:'單據號',
      submit:'提交',
      form_No_reg_mes:'必須是HT開頭',
      form_No_reg_mes2:'必須是HTL開頭',
      form_No_reg_mes3:'必須是HTO開頭',
      type_required_err:'單號類型不能為空',
      form_No_length_err:'單據長度不足15位',
      startTime_dateNotBigger_err:'結束時間必須遲於開始時間',
      endTime_DateNotSmaller_err:'結束時間必須遲於開始時間'
    },
    simple_Chinese:{
      title:'查询',
      form_type:'单据类型',
      startTime:'假单管理',
      endTime:'考勤查询',
      form_No:'单据号',
      submit:'提交',
      form_No_reg_mes:'必须是HT开头',
      form_No_reg_mes2:'必须是HTL开头',
      form_No_reg_mes3:'必须是HTO开头',
      type_required_err:'单号类型不能为空',
      form_No_length_err:'单据长度不足15位',
      startTime_dateNotBigger_err:'结束时间必须迟于开始时间',
      endTime_DateNotSmaller_err:'结束时间必须迟于开始时间'
    }
  };
  static holidayDetailComponent = {
    traditional_Chinese:{
      title:'個人維護詳情',
      STADATE:'特休假生效日期',
      canUse:'可用假天數',
      used:'已用假天數'
    },
    simple_Chinese:{
      title:'个人维护详情',
      STADATE:'特休假生效日期',
      canUse:'可用假天数',
      used:'已用假天数'
    }
  };
  static leaveMessageMenuComponent = {
    traditional_Chinese:{
      title:'考勤查詢',
      swipe_note:'刷卡記錄',
      attendance_month:'出勤月檔',
      attendance_detail:'出勤狀況明細'
    },
    simple_Chinese:{
      title:'考勤查詢',
      swipe_note:'刷卡记录',
      attendance_month:'出勤月档',
      attendance_detail:'出勤状况明细'
    }
  };
  static listFilterComponent = {
    traditional_Chinese:{
      form_No:'單號',
      startTime:'開始時間',
      endTime:'結束時間',
      businessTime:'出差時間',
      OTtime:'申請加班時間',
      trueCount:'實際加班',
      type:'類別',
      leave_No:'請假單據號',
      callback_reason:'銷假原因',
      search_placeholder:'單據號篩選'
    },
    simple_Chinese:{
      form_No:'单号',
      startTime:'开始时间',
      endTime:'结束时间',
      businessTime:'出差时间',
      OTtime:'申请加班时间',
      trueCount:'实际加班',
      type:'类别',
      leave_No:'请假单据号',
      callback_reason:'销假原因',
      search_placeholder:'单据号筛选'
    }
  };
  static formListComponent = {
    traditional_Chinese:{
      exit:'退出'
    },
    simple_Chinese:{
      exit:'退出'
    }
  };
  static leaveSubComponent = {
    traditional_Chinese:{
      title:'假單管理',
      for_leave:'請假',
      for_callback:'銷假',
      for_business:'公出',
      for_callback_tip:'無可銷假的假單'
    },
    simple_Chinese:{
      title:'假單管理',
      for_leave:'请假',
      for_callback:'销假',
      for_business:'公出',
      for_callback_tip:'无可销假的假单'
    }
  };
  static callbackLeaveFormComponent = {
    traditional_Chinese:{
      unSave_title:'新建銷假單',
      saved_title:'銷假單詳情',
      form_status:'單據狀態',
      form_No:'單據編號',
      sign:'送簽',
      save:'保存',
      confirm:'確認',
      cancle:'取消',
      sign_list:'簽核名單',
      leave_No:'取消假單 ',
      reason:'取消原因',
      leave_No_required_err:'請假單號不能為空',
      reason_required_err:'原因不能為空',
      reason_minlength_err:'原因長度不能少於2位',
    },
    simple_Chinese:{
      unSave_title:'新建销假单',
      saved_title:'销假单详情',
      form_status:'单据状态',
      form_No:'单据编号',
      sign:'送签',
      save:'保存',
      confirm:'确认',
      cancle:'取消',
      sign_list:'签核名单',
      leave_No:'取消假单 ',
      reason:'取消原因',
      leave_No_required_err:'请假单号不能为空',
      reason_required_err:'原因不能為空',
      reason_minlength_err:'原因長度不能少於2位',
    }
  };
  static businessFormComponent = {
    traditional_Chinese:{
      unSave_title:'新建公出單',
      saved_title:'公出單詳情',
      form_status:'單據狀態',
      form_No:'單據編號',
      sign:'送簽',
      save:'保存',
      confirm:'確認',
      cancle:'取消',
      sign_list:'簽核名單',
      colleague:'代理人',
      autoSet:'啟用代理',
      businessTime:'公出日期',
      startTime:'開始時間',
      endTime:'結束時間',
      hourCount:'時數',
      dayCount:'公出天數',
      reasonType:'公出類型',
      reason:'公出原因',
      sign_success:'送簽成功',
      save_success:'表單保存成功',
      reasonType_required_err:'請選擇公出類型',
      businessTime_required_err:'公出日期不能為空',
      reason_required_err:'原因不能為空',
      reason_minlength_err:'原因長度不能少於2位',
      startTime_required_err:'開始時間不能為空',
      startTime_timeSmaller_err:'結束時間必須遲於開始時間',
      endTime_required_err:'結束時間不能為空',
      endTime_timeBigger_err:'結束時間必須遲於開始時間',
      colleague_required_err:'請選擇代理人'
    },
    simple_Chinese:{
      unSave_title:'新建公出单',
      saved_title:'公出单详情',
      form_status:'单据状态',
      form_No:'单据编号',
      sign:'送签',
      save:'保存',
      confirm:'确认',
      cancle:'取消',
      sign_list:'签核名单',
      colleague:'代理人',
      autoSet:'启用代理',
      businessTime:'公出日期',
      startTime:'开始时间',
      endTime:'结束时间',
      hourCount:'时数',
      dayCount:'公出天数',
      reasonType:'公出类型',
      reason:'公出原因',
      sign_success:'送签成功',
      save_success:'表单保存成功',
      reasonType_required_err:'请选择公出类型',
      businessTime_required_err:'公出日期不能为空',
      reason_required_err:'原因不能为空',
      reason_minlength_err:'原因长度不能少于2位',
      startTime_required_err:'开始时间不能为空',
      startTime_timeSmaller_err:'结束时间必须迟于开始时间',
      endTime_required_err:'结束时间不能为空',
      endTime_timeBigger_err:'结束时间必须迟于开始时间',
      colleague_required_err:'请选择代理人',
    }
  };
  static overTimeFormComponent = {
    traditional_Chinese:{
      unSave_title:'新建加班單',
      saved_title:'加班單詳情',
      form_status:'單據狀態',
      form_No:'單據編號',
      sign:'送簽',
      save:'保存',
      confirm:'確認',
      cancle:'取消',
      sign_list:'簽核名單',
      duty_type: '班別',
      OTtime:'加班日期',
      startTime:'起始時間',
      endTime:'結束時間',
      OTCount:'加班時數',
      reasonType:'工作紀要',
      reason:'加班原因',
      sign_success:'送簽成功',
      save_success:'表單保存成功',
      reasonType_required_err:'請選擇加班類型',
      OTtime_required_err:'加班日期不能為空',
      reason_required_err:'原因不能為空',
      reason_minlength_err:'原因長度不能少於2位',
      startTime_required_err:'開始時間不能為空',
      startTime_timeSmaller_err:'結束時間必須遲於開始時間',
      endTime_required_err:'結束時間不能為空',
      endTime_timeBigger_err:'結束時間必須遲於開始時間'
    },
    simple_Chinese:{
      unSave_title:'新建加班单',
      saved_title:'加班单详情',
      form_status:'单据状态',
      form_No:'单据编号',
      sign:'送签',
      save:'保存',
      confirm:'确认',
      cancle:'取消',
      sign_list:'签核名单',
      duty_type: '班别',
      OTtime:'加班日期',
      startTime:'起始时间',
      endTime:'结束时间',
      OTCount:'加班时数',
      reasonType:'工作纪要',
      reason:'加班原因',
      sign_success:'送签成功',
      save_success:'表单保存成功',
      reasonType_required_err:'请选择加班类型',
      OTtime_required_err:'加班日期不能为空',
      reason_required_err:'原因不能为空',
      reason_minlength_err:'原因长度不能少于2位',
      startTime_required_err:'开始时间不能为空',
      startTime_timeSmaller_err:'结束时间必须迟于开始时间',
      endTime_required_err:'结束时间不能为空',
      endTime_timeBigger_err:'结束时间必须迟于开始时间'
    }
  };

  static LeaveFormComponent = {
    traditional_Chinese:{
      unSave_title:'新建請假單',
      saved_title:'請假單詳情',
      form_status:'單據狀態',
      form_No:'單據編號',
      reasonType:'假別',
      autoSet:'啟用代理',
      startDate:'開始日期',
      endDate:'結束日期',
      startTime:'開始時間',
      endTime:'結束時間',
      colleague:'代理人',
      leave_hour:'時數',
      leave_day:'請假天數',
      reason:'請假原因',
      sign:'送簽',
      save:'保存',
      sign_list:'簽核名單',
      reasonType_required_err:'請選擇請假類型',
      colleague_required_err:'請選擇代理人',
      reason_required_err: '原因不能為空',
      reason_minlength_err: '原因長度不能少於2位',
      sign_success:'送簽成功',
      save_success:'表單保存成功',
      time_err:'開始時間必須早於結束時間',
      colleague_placeholder:'請輸入2位以上的工號進行查詢',
      confirm:'確認',
      cancle:'取消'
    },
    simple_Chinese:{
      unSave_title:'新建请假单',
      saved_title:'请假单详情',
      form_status:'单据状态',
      form_No:'单据编号',
      reasonType:'假别',
      autoSet:'启用代理',
      startDate:'开始日期',
      endDate:'结束日期',
      startTime:'开始时间',
      endTime:'结束时间',
      colleague:'代理人',
      leave_hour:'时数',
      leave_day:'请假天数',
      reason:'请假原因',
      sign:'送签',
      save:'保存',
      sign_list:'签核名单',
      reasonType_required_err:'请选择请假类型',
      colleague_required_err:'请选择代理人',
      reason_required_err: '原因不能为空',
      reason_minlength_err: '原因长度不能少于2位',
      sign_success:'送签成功',
      save_success:'表单保存成功',
      time_err:'开始时间必须早于结束时间',
      colleague_placeholder:'请输入2位以上的工号进行查询',
      confirm:'确认',
      cancle:'取消'
    }
  };

}
